### ISSUE TITLE
TPU support

### ISSUE THREAD

**Issue by arrow53** [mirzak/meta-coral#1]
@mirzak this isn't an issue, but I was wondering if you could comment on whether this layer supports the TPU? For instance, do any of the Python calls work?

https://coral.withgoogle.com/docs/edgetpu/api-intro/

This is great you started this project.

**Comment by mirzak** [comment]
Hi @arrow53, I have not yet tested the TPU and the python API is not installed yet.

This is the next thing that I intend to do, trying to port this over from Mendel OS.

**Comment by btashton** [comment]
You need the binary libs from here https://coral.googlesource.com/edgetpu-native/+/refs/heads/release-chef/libedgetpu/ and then you can use them with meta-tensorflow

**Comment by mirzak** [comment]
Yeah I would not expect it to take much and just port their [existing instructions](https://coral.withgoogle.com/docs/accelerator/get-started/) which also includes the python module,

```
cd ~/

wget https://dl.google.com/coral/edgetpu_api/edgetpu_api_latest.tar.gz -O edgetpu_api.tar.gz --trust-server-names

tar xzf edgetpu_api.tar.gz

cd edgetpu_api

bash ./install.sh
```

to an recipe.

**Comment by mirzak** [comment]
Also a second/third resources is the deb package that is created in Mendel OS,

https://coral.googlesource.com/edgetpu/+/refs/heads/release-chef

**Comment by arrow53** [comment]
@mirzak @btashton so, this ended up working fine. I used the installation instructions for a raspberry pi as a guide.

https://coral.withgoogle.com/docs/accelerator/get-started/

The only real trick was i had to include some python packages and clang in order to get libc++ libraries. I'm unclear licensing wise if the edgetpu library can be pulled into this layer. But, it's really just the .so that needs to be put in place so doing that after the fact isn't that hard.

**Comment by mirzak** [comment]
Thanks for the update. Did you create a recipe that you can share? I can investigate if if it is ok to pull in here

**Comment by arrow53** [comment]
i'll work on it. Is it ok license wise to pull in binaries?

I'm fixated on trying to get the camera to work with this layer, but once I do that I'll revisit.

**Comment by mirzak** [comment]
> i'll work on it. Is it ok license wise to pull in binaries?

This should be just fine. We just need to tag the correct license for the binaries. Which is [this](https://coral.googlesource.com/edgetpu/+/refs/heads/release-chef/libedgetpu/LICENSE.txt), at least this text is used for the Debian package.

**Comment by mirzak** [comment]
I create a quick prototype of the TPU recipe,

https://github.com/mirzak/meta-coral/commit/aea555dfaf93e09b3dacff47cc6e244a51352d70

Still needs some work but I will try to finish it up.

**Comment by mirzak** [comment]
Yeah, knew about meta-clang requirement (this will also be a requirement for this layer once the recipes are added).

I have made some progress and gotten everything to compile at least (lib, python API + demo applications). 

Next is some run time testing and documentation updates

**Comment by mirzak** [comment]
This was added in https://github.com/mirzak/meta-coral/pull/5

**Comment by qkaseman** [comment]
@mirzak how were you able to test the `edgetpu-demo.bb` file (specifically how were you able to run the resulting file on the coral)? I've included it in a build by adding `IMAGE_INSTALL_append += " edgetpu-demo"` to `local.conf` and it builds successfully and is in the image.

However, trying to run `edgeput_demo --stream` or `edgetpu_demo --device` initially results in `ValueError: Namespace Gtk not available`. Adding `gtk+3` to `edgetpu-demo.bb` `RDEPENDS_${PN}` solves that issue. 

Unfortunately, it then fails with `Gtk-WARNING **: <time>: cannot open display`, which I have not been able to resolve that. I see terminal output on the HDMI but no WM/DE.
