### ISSUE TITLE
Update libedgetpu to github location

### ISSUE THREAD

**Issue by mirzak** [mirzak/meta-coral#16]
Project location has changed to:

https://github.com/google-coral/edgetpu

**Comment by mirzak** [comment]
The old location is still valid, so no rush on this one. Also github location only contains `diploria` release tags which I assume would be the next release.

**Comment by mbrooksx** [comment]
Agreed not a huge rush but everything is migrating to GitHub and the googlesource location will be removed. Note that the latest release is "eel" (tags are on GitHub for it) and moving forward releases will be on GitHub and be alphabetical.

**Comment by mirzak** [comment]
> Agreed not a huge rush but everything is migrating to GitHub and the googlesource location will be removed. Note that the latest release is "eel" (tags are on GitHub for it) and moving forward releases will be on GitHub and be alphabetical.

Thanks, this is useful information

**Comment by mathieugalle** [comment]
Hi,

I just did the same task of updating to the new libedgetpu repo for a custom layer (I am not using meta-coral, but the information on this repository was helpful).

Here is what I needed to change : 


> HOMEPAGE = "https://github.com/google-coral/libedgetpu"
> SRC_URI = "https://github.com/google-coral/libedgetpu/releases/download/release-grouper/edgetpu_runtime_20221024.zip"
> SRC_URI[md5sum] = "0239aa3a4091dff542aaa6707b2b7933"
> SRC_URI[sha256sum] = "7f17d85e6f21ec861af3f9168043a7ec351b80e08c9f168013ab68e99410aee2"
> 
> LICENSE = "Apache-2.0"
> LIC_FILES_CHKSUM = "file://libedgetpu/LICENSE;md5=deb6c9c1780e35838c5719d31c55ca18"


They removed the ".txt" extension on the LICENSE file, it took me some time to understand the problem on the LICENSE hash.

Hope this helps :-)

**Comment by mirzak** [comment]
Superseded by #63 and #64
