### ISSUE TITLE
source of u-boot

### ISSUE THREAD

**Issue by arrow53** [mirzak/meta-coral#2]
@mirzak this isn't an issue, just some confusion. i'm trying to use your generated u-boot but then pull my devicetree/kernel off the network via tftp. 

I noticed that the wic.gz creates a boot partition with a boot.scr, Image file, and a few dtbs. Where is u-boot?

I found that I can't even overwrite the bootcmd u-bboot env variable unless the Image file is there, which is really odd. But, isn't Image just the kernel?

sorry if this is not relevant to the layer and feel free to close if it's not.

**Comment by mirzak** [comment]
> I noticed that the wic.gz creates a boot partition with a boot.scr, Image file, and a few dtbs. Where is u-boot?

U-boot stored "outside" of the boot partition, between start of disk and start of boot part. This is what this line in the wks file translates to.

     https://github.com/mirzak/meta-coral/blob/master/wic/coral-bootpart.wks.in#L16

> I found that I can't even overwrite the bootcmd u-bboot env variable unless the Image file is there, which is really odd. But, isn't Image just the kernel?

Unsure what you mean with this. This particle configuration is using the "distro_bootcmd" which probes various locations for various ways to boot. One of them is the `boot.scr`, if it finds it it will run and the `boot.scr` should result in a boot.

**Comment by arrow53** [comment]
@mirzak thanks for the explanation. I've never seen u-boot stored outside the boot partition. Very interesting.

The genesis of my problem is I believe the u-boot source overwrites the bootcmd, regardless if it has been edited, if booting from an sd card. As I wanted to just boot u-boot off the sd card I edited the source and reflashed the sd card. There's probably a better way. But, now at least I understand a bit better so thanks.
