### ISSUE TITLE
Known good setup

### ISSUE THREAD

**Issue by mbrooksx** [mirzak/meta-coral#25]
Hi Mirza,

Thanks for implementing this! I'm trying to get a basic setup where I can test the latest ML release (as you have in a bug, pulling from GitHub). The README mentions using the Master branches for my manifest but I see you have bugs in Zues.

Should I expect this to work at master? If not, should I be using warrior? On master I see coral layer concerns (without adding dunfell to layer.conf compat) as well as dtc-145 issues in u-boot-coral_2017.03.bb (and I'm still slogging through to try to get it all working).

Thanks!

**Comment by mirzak** [comment]
Hi @mbrooksx ,

I would recommend using the `warrior` branch which is the current stable release. Also check out the [wiki](https://github.com/mirzak/meta-coral/wiki) which covers some additional steps to get all components in place and how to run the example models.

`master` branch is currently WIP and primary trying to get `master` to work together with `zeus` to get a working `zeus` branch before starting to work on `dunfell`.

**Comment by mbrooksx** [comment]
Hi @mirzak ,

Thanks - I'm able to boot the board with warrior (I was attempting warrior for FSL and master for meta-coral, cause a lot of bbappend mismatch). 

Sorry for the newbie questions, one last issue I'm having is getting the python packages (and specifically I'd like to see python3-edgetpu) in action. However I noticed that the packages are excluded:

DEBUG: EXCLUDE FROM WORLD: virtual:nativesdk:/usr/local/google/home/michaelbrooks/yocto_warrior/sources/meta-coral/recipes-support/python/python3-edgetpu.bb
DEBUG: EXCLUDE FROM WORLD: virtual:native:/usr/local/google/home/michaelbrooks/yocto_warrior/sources/meta-coral/recipes-support/python/python3-edgetpu.bb

I can't find the reason why (I'm make core-image-base, but the same with weston) - perhaps license mismatch for Apache?

Thanks again!

**Comment by mirzak** [comment]
Can you share a bit more about your environment? I have not seen similar problems when testing

**Comment by mbrooksx** [comment]
I'm running Debian, it's a Stretch derivative (designed for Google employees, I'm on the Coral team) on a 5.2 kernel. I followed the steps listed on the warrior branch, initializing the repo with the warrior manifest then checking out clang and coral with the warrior branches. Nothing else is changed (with the exception of skipping the sanity test since it doesn't like my access permissions despite matching the u+rwx and a+rx request).

Thanks!

**Comment by mirzak** [comment]
Would it be possible to share a more complete log? Do not have much to go on and nothing wrong with your environment.

I do not know what type of permissions you have, but e.g running `bitbake` with `sudo` would probably mess things up pretty bad and best would be to start over.

**Comment by mbrooksx** [comment]
[warrior_coral.tar.gz](https://github.com/mirzak/meta-coral/files/4458273/warrior_coral.tar.gz)

Haven't been running with sudo, permissions are correct just can't convince the sanity checker of it.

**Comment by mirzak** [comment]
The logs look good to me, can you share the output of

```
cat tmp/deploy/images/coral-dev/core-image-base-coral-dev.manifest
```

It should contain the `python3-edgetpu` if you added it trough `IMAGE_INSTALL` by e.g putting the following in your `local.conf` file

```
IMAGE_INSTALL_append = " \
    python3-edgetpu \
    python3-edgetpu-examples \
"
```

The `EXCLUDE FROM WORLD:` should not really matter, as you are not running a `world` build.

Another way to debug what you have in your `IMAGE_INSTALL` is e.g,

```
bitbake core-image-base -e | grep ^IMAGE_INSTALL
```

This is a good way to make sure that your desired actually are being applied.

**Comment by mbrooksx** [comment]
Thanks that was really useful. I copied the recipe on another bug to make a fsl-multimedia-full with edgetpu added. Unfortunately in the last week since I was first building there now appears to be issues with the GPT on the WIC image but I think we can close this bug. Thanks agian!
