### ISSUE TITLE
ttymxc not available

### ISSUE THREAD

**Issue by johnny-jiang-000** [mirzak/meta-coral#36]
Hi mirzak,

<p>I installed coral-demo-image on my coral-dev board. When I try to use uart device the linux kernel return the error message<br>

> [ 9196.589990] imx-sdma 30bd0000.sdma: sdma firmware not ready!
[ 9196.595673] imx-uart 30890000.serial: Prepare for the RX slave dma failed!

Both ttymxc1 and ttymxc2 return the same error. </p>

**Comment by mirzak** [comment]
What Yocto version are you on?

Can you post the result of `dmesg | grep sdma`. 

I suspect that either the SDMA firmware files are missing or incompatible with the kernel cora-dev board is using. This is typically provided by the [firmware-imx package](https://github.com/Freescale/meta-freescale/tree/zeus/recipes-bsp/firmware-imx)

**Comment by johnny-jiang-000** [comment]
Thanks for reply. I took reference from here and solved the problem.  It need to include sdma-imx7d.bin firmware into kernel image compilation so the sdma firmware can correctly loaded on boot. Johnny Jiang  发件人: Mirza Krak发送时间: Tuesday, June 30, 2020 7:36收件人: mirzak/meta-coral抄送: johnny-jiang-000; Author主题: Re: [mirzak/meta-coral] ttymxc not available (#36) What Yocto version are you on?Can you post the result of dmesg | grep sdma.I suspect that either the SDMA firmware files are missing or incompatible with the kernel cora-dev board is using. This is typically provided by the firmware-imx package—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mirzak** [comment]
Filtering above message:

> Thanks for reply. I took reference from here and solved the problem.  It need to include sdma-imx7d.bin firmware into kernel image compilation so the sdma firmware can correctly loaded on boot.

**Comment by johnny-jiang-000** [comment]
> Filtering above message:
> 
> > Thanks for reply. I took reference from here and solved the problem.  It need to include sdma-imx7d.bin firmware into kernel image compilation so the sdma firmware can correctly loaded on boot.

omg is that what will happen if reply using win10 mail app.....
btw I found a similar case and take solution from here (https://community.nxp.com/thread/531049#comment-1310375)
