### ISSUE TITLE
Hardknott layers compatible which doesn't exist on repo

### ISSUE THREAD

**Issue by Dibyajyoti227** [mirzak/meta-coral#56]
I am trying to add this layer and getting error,
ERROR: Layer coral-bsp is not compatible with the core layer which only supports these series: hardknott (layer is compatible with mickledore)

I don't see any hardknott branch on the repo. Anyone else knows how to handle this error?

**Comment by mirzak** [comment]
hardknott is EOL by now, closing. pull-request incoming to add compatibility with current and upcoming releases.
